name: Egg Error/Bug
description: Report an issue for an egg
title: "[Egg problem]: "
labels: ["bug", "egg"]
body:
  - type: markdown
    attributes:
      value: |
        Have you tried delete and install again?  
        Make sure there are no existing bug reports by searching the [repository issues](https://github.com/kry008/pterodactyl-io-ARM-eggs/labels/bug)
  - type: input
    id: Egg link
    attributes:
      label: Link to egg from this repo
      description: https://github.com/kry008/pterodactyl-io-ARM-eggs/tree/main/nodejs/expressjs
      placeholder: https://github.com/kry008/pterodactyl-io-ARM-eggs/.../...
      validations:
        required: true
  - type: dropdown
    id: newProblem
    attributes:
      label: Is this problem NOT mention in Known issue in that egg?
      description: All eggs have info about known problems
      options:
        - Yes
        - No
    validations:
      required: true
  - type: dropdown
    id: arch
    attributes:
      label: CPU architecture?
      description: ARM64, ARM Oracle, AMD64...
      options:
        - ARM64
        - ARM32
        - ARM Oracle
        - AMD64
        - Other (write below)
    validations:
      required: true
  - type: input
    id: otherArch
    attributes:
      label: If you choose Other in previus
      validations:
        required: false
  - type: input
    id: Egg link
    attributes:
      label: Link to egg from this repo
      description: https://github.com/kry008/pterodactyl-io-ARM-eggs/tree/main/nodejs/expressjs
      placeholder: https://github.com/kry008/pterodactyl-io-ARM-eggs/.../...
      validations:
        required: true
  - type: dropdown
    id: archWorking
    attributes:
      label: In main Readme.MD this egg should work? (is architecture ✅?)
      description: All eggs have info about known problems
      options:
        - ✅ - Working
        - ❔- Not tested yet but should work
        - ❌ - Don't work
        - There isn't my
    validations:
      required: true
  - type: input
    id: panel-version
    attributes:
      label: Panel Version
      description: Version number of your Panel (latest is not a version)
      placeholder: 1.x.x
    validations:
      required: true
  - type: input
    id: wings-version
    attributes:
      label: Wings Version
      description: Version number of your Wings (latest is not a version)
      placeholder: 1.x.x
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen
      placeholder: Install the server, start it, play
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened instead
      placeholder: Server crashed with error X
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps To Reproduce
      description: Step by step what to do to cause the issue
      placeholder: |
        Step 1 Set version to latest
        Step 2 install
        Step 3 Receive error X or Y
    validations:
      required: true
  - type: input
    id: install-logs
    attributes:
      label: Install logs
      description: |
        Run the command below on the SSH terminal of your Wings machine and provide the link to logs.
        
        ```
        tail -n 1000 $(ls -Alrt /var/log/pterodactyl/install/*.log | tail -1 | sed 's/  */ /g' | cut -s -d' ' -f9) | nc pteropaste.com 99
        ```
      placeholder: |
        https://pteropaste.com/exampleLogs
    validations:
      required: true
