name: New Egg
description: Request for a new egg
title: "[New]:"
labels: ["new egg", "documentation", "egg"]
body:
  - type: markdown
    attributes:
      value: |
        ## Make sure that this game isn't requested by someone else or is pending in Pull Request
        You can use this form when you have a new game or application and would like to add. You will need information such as: 
        1. What application? 
        1. Link to documentation.
        1. Is this app from the Steam store. 
        1. Does it work on Linux and ARM64.
  - type: input
    id: name
    attributes:
      label: App/Game name
    validations:
      required: true
  - type: input
    id: link-app
    attributes:
      label: Link to app/game
    validations:
      required: true
  - type: input
    id: link-wiki
    attributes:
      label: Link to app/game wiki
    validations:
      required: true
  - type: input
    id: link-install
    attributes:
      label: Link to app/game how to install
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: The processor architectures it is SURE to run on
      options:
      - label: ARM64
      - label: ARM32
      - label: ARM Oracle
      - label: AMD64
    validations:
      required: true
  - type: textarea
    attributes:
      label: Other architectures
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References?  
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
